apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  type: NodePort  # Use LoadBalancer if in cloud
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 30080   # Access via localhost:30080 in minikube/kind
