name: Angular Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # 1 Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2 Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3 Install Angular CLI globally
      - name: Install Angular CLI
        run: npm install -g @angular/cli@15.1.6

      # 4 Install dependencies
      - name: Install npm dependencies
        run: npm install

      # 5 Build Angular app
      - name: Build Angular App
        run: ng build --prod

      # 6 Deploy to server via SCP
      - name: Copy dist folder via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./dist/*"
          target: "/var/www/html/"
          strip_components: 1
