name: Angular Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install Angular CLI
      - name: Install Angular CLI
        run: npm install -g @angular/cli@15.1.6

      # Install dependencies
      - name: Install npm dependencies
        run: npm install

      # Build Angular app
      - name: Build Angular app
        run: ng build

        # Deploy build to server
      - name: Copy dist folder via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/elearning-website/**"
          target: "/var/www/html/elearning-website/"